add_rules("mode.debug", "mode.release")

add_requires("platform-tools 35.0.0")
add_requires("onnxruntime 1.19.2")
add_requires("boost", {configs = {iostreams = true}})
add_requires("ffmpeg")
add_requires("opencv")
add_requires("toml++")
add_requires("tobiaslocker_base64")
add_requires("tl_expected")
add_requires("eigen")
add_requires("magic_enum")
add_requires("cpp-dump")
add_requires("munkres-algorithm")

add_requires("fmt")
add_requires("spdlog", {configs = {fmt_external = true}})

target("CR_Bot.Common", function()
    set_kind("headeronly")
    set_languages("c++17")

    add_packages("platform-tools", {public = true})
    add_packages("onnxruntime", {public = true})
    add_packages("boost", {public = true})
    add_packages("ffmpeg", "opencv", {public = true})
    add_packages("toml++", {public = true})
    add_packages("tobiaslocker_base64", {public = true})
    add_packages("tl_expected", {public = true})
    add_packages("fmt", "spdlog", {public = true})
    add_packages("eigen", {public = true})
    add_packages("magic_enum", {public = true})
    add_packages("cpp-dump", {public = true})
    add_packages("munkres-algorithm", {public = true})

    add_headerfiles("include/(**.hpp)")
    add_includedirs("include", {public = true})

    add_deps("av", "emulator", {public = true})
end)
