[adb]
# The IP address of your device or emulator.
# Use 127.0.0.1 for a local emulator. If you're connecting to a physical device,
# make sure to use the device's IP address.
ip = "127.0.0.1"

# The serial number of your device
# Use adb devices to obtain it
device_serial = "emulator-5554"
